### ISSUE TITLE
Пользователь всё-равно может использовать запрещенный трекер.

### ISSUE THREAD

**Issue by Pr-Mex** [atlascoder/tracker_hider#10]
Использую следующее:
windows server 2012 standard
ruby 2.0.0-x64
rails 4.2.4
redmine v3.1.1

Попробовал все три ветки плагина tracker_hider
Закладка, в которой можно настраивать правила появилась только при использовании ветки **global_roles**. Для остальных двух веток на странице проекта так и не появилась закладка для создания правил.

Поэтому опишу действия для ветки **global_roles**.
При попытке создать правило происходит следующее:

Когда мы хотим запретить роли "Пользователь" использовать трекер "Мой трекер"
Тогда мы Создаём правило для роли "Пользователь" и трекера "Мой трекер"
И логинемся под пользователем
И переходим на страницу проекта "Мой проект"
Тогда мы больше не видим задач, которые относятся к трекеру "Мой трекер"
Но мы всё-равно можем создавать новые задачи с трекером "Мой трекер"

Надеюсь я понятно описал проблему.

**Comment by atlascoder** [comment]
Действительно, `global_roles` перестала нормально работать, видимо после внесенных правок. Эта ветка мной не используется и поэтому не тестировалась. Но она будет исправлена в ближайшие дни, спасибо за указание на ошибку.

Для остальных веток, страница управления правилами находится в настройках каждого проекта и доступна для ролей, которым такое управление разрешено. Кроме этого, Эта страница, и функция скрытия трекеров, включается при включении соответствующего модуля настройках проекта.
Судя по вопросу, вам нужна ветка `fix_trackers`.

**Comment by Pr-Mex** [comment]
Ещё раз попробовал ветку fix_trackers.
Права для роли - дал.
![image](https://cloud.githubusercontent.com/assets/8627416/12917618/6eddde96-cf4b-11e5-996c-835021d4392c.png)

В проекте добавил модуль 
![image](https://cloud.githubusercontent.com/assets/8627416/12917634/87b2bffe-cf4b-11e5-89ee-ef0bd6409a2e.png)

Но новая закладка в проекте (в настройках) не появилась.
Пользователю роль в проекте назначена.

**Comment by atlascoder** [comment]
Ок, я сначала исправлю `global_roles`, возможно в процессе, что-то обнаружится. `fix_trackers` работает и проверен на нескольких конфигурациях, но возможно у вас что-то новое. Какая СУБД используется и для полноты картины скиньте конфигурацию из Администрирование - Информация
![image](https://cloud.githubusercontent.com/assets/9552354/12918109/f6c3d0a0-cf45-11e5-9d00-c8b263777b76.png)

**Comment by Pr-Mex** [comment]
СУБД - PostgreSQL  9.4.5

Вот информация:

Environment:
  Redmine version                3.1.1.devel
  Ruby version                   2.0.0-p645 (2015-04-13) [x64-mingw32]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Filesystem                     
Redmine plugins:
  a_common_libs                  1.1.6
  advanced_roadmap_v2            2.4.2
  clipboard_image_paste          1.10
  custom_menu                    1.5.0
  extra_queries                  2.0.0
  global_roles                   2.0.0
  planner                        0.5
  progressive_projects_list      2.0.1
  quick_edit                     0.0.9
  quick_view                     0.1.0
  recurring_tasks                2.0.0-pre
  redmine_agile                  1.3.9
  redmine_backlogs               v1.0.6
  redmine_ckeditor               1.1.2
  redmine_code_review            0.7.0
  redmine_contacts               4.0.1
  redmine_contacts_helpdesk      3.0.0
  redmine_custom_workflows       0.1.4
  redmine_dmsf                   1.5.4
  redmine_graphs                 0.1.0
  redmine_issue_tabs             1.1.0
  redmine_lightbox2              0.2.2
  redmine_mail_reminder          3.0.0.0001
  redmine_monitoring_controlling 0.1.1
  redmine_per_project_formatting 0.0.4
  redmine_products               2.0.0
  redmine_webhook                0.0.1
  redmine_work_time              0.3.0
  redmine_workflow_enhancements  0.4.0
  rm_user_mentions               1.0.0
  rmplus_devtools                1.0.0
  stuff_to_do_plugin             0.4.2
  tracker_hider                  0.0.1
  unread_issues                  1.5.0
  usability                      1.3.0

**Comment by atlascoder** [comment]
Прошу прощения за задержку.. Проверьте эту версию global_roles

**Comment by Pr-Mex** [comment]
Проверил. Теперь работает.
Спасибо!

**Comment by Pr-Mex** [comment]
Проверено под redmine 3.2.

**Comment by atlascoder** [comment]
Спасибо за обратную связь!

И все же по поводу закладки для другой ветки - хотелось бы уточнить кое-что. Я вижу у вас достаточно много плагинов, часть из которых работает с панелью настроек проекта.Я предполагаю, что какой-то из них что-то заменяет в этой панели. Плагинов слишком много и просматривать код всех не вижу возмжным, поэтому прошу вас, если не сильно трудно, проверить ветку fix_trackers на проекте с отключенными модулями плагинов. Таким образом можно сократить область поиска проблемы.
