### ISSUE TITLE
bit confusing with branches...

### ISSUE THREAD

**Issue by amityk77** [atlascoder/tracker_hider#14]
Hello,

As mentioned there are 3 branches for this plugin, I have installed from "master", but the plugin refuses to work, after creating rules.  Trackers are still visible.

After analyzing repositories, it seems that the other two branches have different bug fixes.

I am not sure which one is the latest with all the fixes.?

Please Help...

**Comment by atlascoder** [comment]
Hello,

agree, there is some mess with branches, but I made different Readme for each branch and you can find the difference. Briefly:

- master_branch - hides issues under trackers for certain roles within particular project
- fix_tracker - hides not only issuers but trackers as well (e.g. from issue creating dialog, e.t.c)
- global_roles - similar to fix_trackers but for roles globally, not on the particular project

TThere wasn't comprehensive testing and bugs are possible. If it doesn't work, please, post more info. Firstly, used DB engine. Also, check if module is enabled. And It wasn't tested (by me) for groups of users..

**Comment by amityk77** [comment]
Thanks atlascoder ... 

one of the branch "fix_tracker" worked for me... :)

Good Work... !!! :+1:
