### ISSUE TITLE
Feature - Disabling tracker/issue type visibility when creating New Issue

### ISSUE THREAD

**Issue by mko-ilim** [atlascoder/tracker_hider#9]
Hello,
I suggest one improvement - disabling visibility of tracker type in drop-down list , when creating new issue. It is based on below scenario:
I configured Tracker Hider (Issue type/Tracker: Bug -> Not visible for my role/user), next I started creating new issue - "Bug" type is visible on drop-down list. I created new Bug - and I have permission denied to it (unauthorized) just after creating the Issue.
Is there any way to turn off "Bug" type visibility on the list? Or maybe there is another possibility of solving this problem?
Some screens:

Tracker Hider settings:
http://i.imgur.com/PFn7e2V.jpg

Creating New Issue:
http://i.imgur.com/iGrnqdU.jpg

Issue Created - Permission Denied:
http://i.imgur.com/CSlsUVK.jpg

Thanks!

**Comment by atlascoder** [comment]
Hi, you can use branch `fix_trackers` that do hiding of hidden trackers

https://github.com/atlascoder/tracker_hider/tree/fix_trackers

**Comment by mko-ilim** [comment]
Thank You @atlascoder,  fix_trackers branch does the trick :)
